### ISSUE TITLE
Unexpected behavior when attempting to multiply 

### ISSUE THREAD

**Issue by fionafibration** [MiningPotatoes/Ohm#13]
https://tio.run/##y8/INfr///C0R437Dq/R@v/fwNDAwMDQ0BAA
To my understanding, the final multiplication shouldn't return those values, but it does

**Comment by nickbclifford** [comment]
<sup>Wow, people are actually still using this?</sup>

What's your intended behavior? The `*` component does not multiply an array (use the `Π` component for that), so this looks to me like it's working as intended.

**Comment by fionafibration** [comment]
I was hoping to multiply the first value by the second.

**Comment by fionafibration** [comment]
It's for measuring the number of trailing 1s in a binary string.

**Comment by nickbclifford** [comment]
Ah, in that case, you'd want to change your code from `Ö⁾ì*` to [`Ö⁾ìΠ`](https://tio.run/##y8/INfr///C0R437Dq85t@D/fwNDAwMDQ0NDAA) to multiply the array.

**Comment by fionafibration** [comment]
Thanks!
