### ISSUE TITLE
`σ` does not work: method `chomp` not found

### ISSUE THREAD

**Issue by lineargraph** [MiningPotatoes/Ohm#2]
[Try it online!](https://tio.run/##y8/I/f8/p@x88///Hqk5OfkK4flFOSlcpgA "Ohm – Try It Online") gives me the following stacktrace if I want to execute `lvσ`: 
```
/opt/ohm/lib/helpers.rb:225:in `input': undefined method `chomp' for nil:NilClass (NoMethodError)
	from /opt/ohm/ohm.rb:16:in `instance_exec'
	from /opt/ohm/ohm.rb:16:in `block (3 levels) in <class:Stack>'
	from /opt/ohm/ohm.rb:16:in `times'
	from /opt/ohm/ohm.rb:16:in `block (2 levels) in <class:Stack>'
	from /opt/ohm/ohm.rb:271:in `call'
	from /opt/ohm/ohm.rb:271:in `exec'
	from /opt/ohm/ohm:32:in `<main>'

Real time: 0.127 s
User time: 0.106 s
Sys. time: 0.017 s
CPU share: 96.53 %
Exit code: 1
```
Without the `σ` everything works fine.

**Comment by nickbclifford** [comment]
This is a known issue that occurs when there are not enough inputs provided
on TIO (or really anywhere that doesn't allow interactive inputs). `σ` pops
2 arguments from the stack, while in this instance, only one is available.

I can't fix this right now as I don't have access to a computer (just my
phone), but I should be able to make a hotfix in a few weeks.

**Comment by nickbclifford** [comment]
This was fixed on `v2` in https://github.com/nickbclifford/Ohm/commit/00de5b08db257b9a6a6c3b6c1d982cbdcad670ec. About to add this specific fix to `master`.

**Comment by nickbclifford** [comment]
Fixed on `master` in https://github.com/nickbclifford/Ohm/commit/c901de79d2d12290dbb14e4fc25468bee09f263e.
