### ISSUE TITLE
[Issue] Inflating Codebase 

### ISSUE THREAD

**Issue by rpsforza** [MiningPotatoes/Ohm#3]
In lib/constants.rb your comment about 0x00-1F in CP437 is not helpful not constructive. Your useless emotions have inflated your codebase to an unusable pile of garbage. The sheer disk space that this comment consumed is too much for most users to handle. Please, on behalf of the entire code golf community, remove this comment.

**Comment by nickbclifford** [comment]
Look at `v2` branch.
