### ISSUE TITLE
[Suggestion]: Make an online encoder/decoder for compressed strings and base-255 numbers. 

### ISSUE THREAD

**Issue by fionafibration** [MiningPotatoes/Ohm#6]
I love this language both for its easy to remember syntax and its extreme usefulness for golfing. However, I am mainly limited to running this using TIO, and I thought that there has to be some way of encoding and decoding the compressed strings and the base-255 numbers. My suggestion is to use https://repl.it for the encoder's code, because it supports pretty much every language you could want. This would really help with using Ohm online. Thanks!

**Comment by fionafibration** [comment]
Or, a better idea would be to make two components which can compress a string and base-255 encode a string, respectively. This is already implemented in Jelly. Then you could simply use the TIO to compress or decompress your strings, and encode or decode base-255 numbers.

**Comment by nickbclifford** [comment]
Base 255 compression can already be done just through components ([TIO](https://tio.run/##y8/INfr/39PI1NTp/38LM3NTYwNLAA)); however, I haven't exposed string compression as a component yet. I'll probably make arbitrary compression/decompression components like Japt has (most likely `·c`/`·d`).
Thanks for reaching out about this!

**Comment by fionafibration** [comment]
When does it update TIO with the new components?

**Comment by nickbclifford** [comment]
Whoops, forgot to ask Dennis to pull. Should be up within the next day or two.
