### ISSUE TITLE
Many block operations not very well explained

### ISSUE THREAD

**Issue by fionafibration** [MiningPotatoes/Ohm#7]
I'm trying to write a program which converts a string into a BrainF*** program which accomplishes the same thing, but I am very confused about the use of the foreach loop. It seems to have extremely weird behavior. For example, in this program I am trying to turn each character into its character code, and then make a string with "+" repeated the number of times of the character code. I then want to concatenate the string ".[-]" for printing. However, it seems to have extremely weird behavior and doesn't work as intended. I was wondering if you could clarify why this is happening?

```
`:.+s×".[-]"↔,  Main circuit
`                     Get array of character codes
 :.+s×              For each item in that array, try and replicate the plus symbol that many times
         ".[-]"↔,   Concatenate the string (that causes BF to print) and print out this partof the BF program
```

**Comment by nickbclifford** [comment]
The foreach loop works in a different way to all the other array looping constructs in that it does not automatically push the looped value to the top of the stack; instead, you have to explicitly push it with `_`. Just replace `s` with `_` in your circuit and it should be good.

Sorry if this wasn't clear in the documentation. I'll make sure to clarify that.

**Comment by fionafibration** [comment]
Oh, thank you for your help!
