### ISSUE TITLE
Hashing and Cryptographic Functions [Suggestion]

### ISSUE THREAD

**Issue by fionafibration** [MiningPotatoes/Ohm#9]
I've noticed that a recurring theme in quite a few cops and robbers challenges is some form of cryptography. I was thinking it would be useful to have some simple hash functions, ie. MD5, SHA-1, SHA-256, SHA-512. Thank you for your consideration and for this amazing golfing language.

**Comment by nickbclifford** [comment]
Interesting idea. How many different functions/algorithms are you thinking? Enough to necessitate a whole new multi-character sequence or should they just be added to the extras sequence?

**Comment by fionafibration** [comment]
Probably just extras, but it would be interesting to have a new prefix character for things like AES-256, SHA-xxx, and other functions. It all really depends on how easy it would be to implement these (ie. use a library or something) and how many would really be applicable. I definitely think MD5 and the SHA family would be a necessity, because of how common they are.

**Comment by nickbclifford** [comment]
Ruby supports MD5, SHA1, SHA256, SHA384, and SHA512 by default. I'll probably add those as a little family in the extras soon.

**Comment by nickbclifford** [comment]
Actually, I might not add SHA384, since I don't think it's used often, and it'd be nice if I could keep the number of components added as a power of 2 so it lines up nicely in the codepage.

**Comment by fionafibration** [comment]
Yeah. 384 is pretty uncommon.
